Homework/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Updated_By_Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Updated By Contact</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Homework/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Is_Synced__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Synced</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Homework/src/classes/ChangeContactsWhichAreNotSyncedTest.cls
@IsTest
public with sharing class ChangeContactsWhichAreNotSyncedTest {
    @TestSetup
    public static void setup() {
        List<Account> accounts = ChangeContactsTestDataHelper.createAccounts(100, true);
        insert accounts;
        List<Contact> contacts = ChangeContactsTestDataHelper.assignContactsToAccounts(accounts);
        if (!contacts.isEmpty()) {
            insert contacts;
        }
    }

    @IsTest
    public static void executeTest() {
        Test.startTest();
        Database.executeBatch(new ChangeContactsWhichAreNotSynced(), 400);
        Test.stopTest();
        System.assertEquals(300, [SELECT COUNT() FROM Contact WHERE Is_Synced__c = TRUE]);
        System.assertEquals(100, [SELECT COUNT() FROM Account WHERE Updated_By_Contact__c = TRUE]);
    }
}